"""Cross-ecosystem contract compliance test.

Validates that a reference `scenes_final.json` generated by the Python pipeline
satisfies all field expectations required by the TypeScript `input-props.ts` types.
This catches silent drift between the two ecosystems.

The test generates a realistic scenes_final.json, validates it with:
1. Python validate_scenes() — structural correctness
2. Field-presence assertions matching every required TypeScript field
3. Type-level assertions (string vs number vs list vs dict)

If this test fails while all other tests pass, the Python↔TypeScript
interface contract has been broken — check input-props.ts for mismatches.
"""

import json
import os
import sys
import pytest

# Add scripts dir to path for import
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from scenes_schema import validate_scenes, SCENE_TYPES, CAPTION_STYLES


def build_reference_scenes_json() -> dict:
    """Build a reference scenes_final.json covering all scene types.
    
    This mirrors the TypeScript ScenesJson interface from input-props.ts
    and serves as the ground truth for the contract.
    """
    return {
        "meta": {
            "article_title": "Reference Test",
            "article_source": "ref/test.md",
            "output": "ref/test.mp4",
            "aspect_ratio": "16:9",
            "width": 1920,
            "height": 1080,
            "fps": 30,
            "total_duration_frames": 900,
            "total_duration_seconds": 30,
            "total_duration_ms": 30000,
            "font_family": "sans-serif",
            "color_theme": {
                "primary": "#1a1a2e",
                "accent": "#e94560",
                "text": "#ffffff",
                "background": "#000000",
            },
        },
        "scenes": [
            {
                "id": "s1",
                "type": "title_card",
                "duration_frames": 150,
                "search_keywords": {"zh": ["测试"], "en": ["test"]},
                "data": {"title": "Hello World", "subtitle": "A Test"},
                "animation": {"type": "fade_in", "duration_frames": 30},
                "narration": {
                    "text": "Hello world",
                    "voice_file": "voice.mp3",
                    "voice_start_ms": 0,
                    "voice_end_ms": 1500,
                    "timestamps": [
                        {"word": "Hello", "start_ms": 0, "end_ms": 500},
                        {"word": "world", "start_ms": 500, "end_ms": 1500},
                    ],
                },
            },
            {
                "id": "s2",
                "type": "chapter_title",
                "duration_frames": 120,
                "search_keywords": {"zh": ["章节"], "en": ["chapter"]},
                "data": {"chapter_number": 1, "title": "Getting Started", "subtitle": "Basics"},
                "narration": {
                    "text": "Chapter one",
                    "voice_file": "voice.mp3",
                    "voice_start_ms": 1500,
                    "voice_end_ms": 3000,
                    "timestamps": [
                        {"word": "Chapter", "start_ms": 1500, "end_ms": 2200},
                        {"word": "one", "start_ms": 2200, "end_ms": 3000},
                    ],
                },
            },
            {
                "id": "s3",
                "type": "stock_footage",
                "duration_frames": 180,
                "search_keywords": {"zh": ["人工智能"], "en": ["AI"]},
                "data": {
                    "media": [
                        {
                            "file": "assets/s3_00.jpg",
                            "source": "pexels",
                            "source_url": "https://pexels.com/photo/1",
                            "type": "image",
                            "width": 1920,
                            "height": 1080,
                            "relevance_score": 0.95,
                        }
                    ],
                    "media_manifest": [],
                    "text_overlays": [
                        {"text": "AI in Action", "position": "bottom", "font_size": 24}
                    ],
                },
                "animation": {"type": "ken_burns", "scale_start": 1.0, "scale_end": 1.1},
                "narration": {
                    "text": "AI is transforming our world",
                    "voice_file": "voice.mp3",
                    "voice_start_ms": 3000,
                    "voice_end_ms": 5000,
                    "timestamps": [
                        {"word": "AI", "start_ms": 3000, "end_ms": 3400},
                        {"word": "is", "start_ms": 3400, "end_ms": 3600},
                        {"word": "transforming", "start_ms": 3600, "end_ms": 4200},
                        {"word": "our", "start_ms": 4200, "end_ms": 4400},
                        {"word": "world", "start_ms": 4400, "end_ms": 5000},
                    ],
                },
            },
            {
                "id": "s4",
                "type": "info_card",
                "duration_frames": 200,
                "search_keywords": {"zh": ["信息"], "en": ["info"]},
                "data": {
                    "layout": "bullet_list",
                    "items": [
                        {"text": "First point", "highlight": True},
                        {"text": "Second point"},
                    ],
                    "columns": [
                        {"title": "Col 1", "content": "Content A", "icon": "star"},
                    ],
                    "quote": "A wise quote",
                    "quote_source": "Expert",
                },
                "narration": {
                    "text": "Here are some key points",
                    "voice_file": "voice.mp3",
                    "voice_start_ms": 5000,
                    "voice_end_ms": 6500,
                    "timestamps": [],
                },
            },
            {
                "id": "s5",
                "type": "code_block",
                "duration_frames": 200,
                "search_keywords": {"zh": ["代码"], "en": ["code"]},
                "data": {"code": "print('hello')", "language": "python", "title": "Example"},
                "narration": {
                    "text": "Print hello",
                    "voice_file": "voice.mp3",
                    "voice_start_ms": 6500,
                    "voice_end_ms": 7500,
                    "timestamps": [],
                },
            },
            {
                "id": "s6",
                "type": "outro",
                "duration_frames": 50,
                "search_keywords": {"zh": ["结尾"], "en": ["outro"]},
                "data": {"cta_text": "Subscribe now", "logo": "logo.png"},
                "narration": {
                    "text": "Thanks for watching",
                    "voice_file": "voice.mp3",
                    "voice_start_ms": 7500,
                    "voice_end_ms": 9000,
                    "timestamps": [],
                },
            },
        ],
        "audio": {
            "voice_file": "voice.mp3",
            "bgm_file": None,
            "bgm_volume": 0.15,
            "voice_volume": 0.9,
        },
        "captions": {
            "enabled": True,
            "style": "karaoke",
            "font_size": 36,
            "position_y": 920,
            "active_color": "#e94560",
            "inactive_color": "#ffffff",
        },
    }


# ── Contract assertions (mirror input-props.ts) ──


def check_field(data: dict, path: str, expected_type: type):
    """Assert that field at dot-separated path exists and is of expected_type."""
    parts = path.split(".")
    current = data
    for part in parts:
        if not isinstance(current, dict) or part not in current:
            pytest.fail(f"Contract breach: missing '{path}' in scenes_final.json")
        current = current[part]
    if not isinstance(current, expected_type):
        pytest.fail(
            f"Contract breach: '{path}' expected {expected_type.__name__}, "
            f"got {type(current).__name__} (value: {current!r})"
        )


class TestContractCompliance:
    """Every assertion here maps to a required field in input-props.ts."""

    def build(self):
        return build_reference_scenes_json()

    # ── Python schema validation ──

    def test_passes_python_schema_validation(self):
        """Must pass scenes_schema.validate_scenes() with zero errors."""
        data = self.build()
        errors = validate_scenes(data)
        assert errors == [], (
            f"Contract breach: Python schema validation failed:\n"
            + "\n".join(f"  - {e}" for e in errors)
        )

    # ── Meta contract ──

    def test_meta_top_level_fields(self):
        data = self.build()["meta"]
        for field in ["article_title", "article_source", "output",
                       "aspect_ratio", "width", "height", "fps",
                       "total_duration_frames", "total_duration_seconds",
                       "font_family"]:
            check_field(data, field, str if field not in ("width", "height", "fps", "total_duration_frames", "total_duration_seconds") else (int, float))

    def test_meta_total_duration_ms(self):
        """total_duration_ms is optional in TS but must be present when backfilled."""
        data = self.build()["meta"]
        check_field(data, "total_duration_ms", (int, float))

    def test_meta_color_theme(self):
        ct = self.build()["meta"]["color_theme"]
        for c in ["primary", "accent", "text", "background"]:
            check_field(ct, c, str)

    # ── Audio contract ──

    def test_audio_fields(self):
        audio = self.build()["audio"]
        for field in ["voice_file", "bgm_volume", "voice_volume"]:
            check_field(audio, field, str if field == "voice_file" else (int, float))

    def test_audio_bgm_file_optional(self):
        """bgm_file can be None (null in JSON)."""
        audio = self.build()["audio"]
        assert "bgm_file" in audio, "Contract breach: missing 'audio.bgm_file'"
        # None (null) is valid — TypeScript type is `string | null`

    # ── Captions contract ──

    def test_captions_fields(self):
        caps = self.build()["captions"]
        for field in ["enabled", "style", "font_size", "position_y",
                       "active_color", "inactive_color"]:
            check_field(caps, field, bool if field == "enabled" else (str if field in ("style", "active_color", "inactive_color") else int))

    def test_captions_style_valid(self):
        caps = self.build()["captions"]
        assert caps["style"] in CAPTION_STYLES, \
            f"Contract breach: captions.style '{caps['style']}' not in {CAPTION_STYLES}"

    # ── Scenes contract ──

    def test_each_scene_has_required_fields(self):
        scenes = self.build()["scenes"]
        assert len(scenes) > 0
        for i, s in enumerate(scenes):
            for field in ["id", "type", "duration_frames", "search_keywords",
                           "data", "narration"]:
                assert field in s, \
                    f"Contract breach: scenes[{i}].{field} missing"

    def test_each_scene_type_valid(self):
        scenes = self.build()["scenes"]
        for i, s in enumerate(scenes):
            assert s["type"] in SCENE_TYPES, \
                f"Contract breach: scenes[{i}].type '{s['type']}' not in {SCENE_TYPES}"

    def test_each_scene_duration_frames_positive(self):
        scenes = self.build()["scenes"]
        for i, s in enumerate(scenes):
            assert isinstance(s["duration_frames"], (int, float)) and s["duration_frames"] > 0, \
                f"Contract breach: scenes[{i}].duration_frames must be positive"

    def test_each_scene_search_keywords(self):
        scenes = self.build()["scenes"]
        for i, s in enumerate(scenes):
            sk = s.get("search_keywords", {})
            assert isinstance(sk, dict) and "zh" in sk and "en" in sk, \
                f"Contract breach: scenes[{i}].search_keywords requires 'zh' and 'en'"

    # ── Narration contract (per scene) ──

    def test_each_scene_narration(self):
        scenes = self.build()["scenes"]
        for i, s in enumerate(scenes):
            nar = s.get("narration", {})
            for f in ["text", "voice_file", "voice_start_ms",
                       "voice_end_ms", "timestamps"]:
                assert f in nar, \
                    f"Contract breach: scenes[{i}].narration.{f} missing"

    def test_each_scene_narration_timestamps_type(self):
        scenes = self.build()["scenes"]
        for i, s in enumerate(scenes):
            ts = s["narration"].get("timestamps", [])
            assert isinstance(ts, list), \
                f"Contract breach: scenes[{i}].narration.timestamps must be list"
            for j, t in enumerate(ts):
                for f in ["word", "start_ms", "end_ms"]:
                    assert f in t, \
                        f"Contract breach: scenes[{i}].narration.timestamps[{j}].{f} missing"

    # ── Per-scene-type data contract ──

    def test_title_card_has_title(self):
        scene = [s for s in self.build()["scenes"] if s["type"] == "title_card"][0]
        check_field(scene["data"], "title", str)

    def test_chapter_title_has_number_and_title(self):
        scene = [s for s in self.build()["scenes"] if s["type"] == "chapter_title"][0]
        check_field(scene["data"], "chapter_number", (int, float))
        check_field(scene["data"], "title", str)

    def test_stock_footage_has_media_list(self):
        scene = [s for s in self.build()["scenes"] if s["type"] == "stock_footage"][0]
        media = scene["data"].get("media", [])
        for i, m in enumerate(media):
            for f in ["file", "source", "type"]:
                assert f in m, \
                    f"Contract breach: stock_footage.data.media[{i}].{f} missing"
            if "source_url" in m:
                assert isinstance(m["source_url"], str)

    def test_info_card_has_layout(self):
        scene = [s for s in self.build()["scenes"] if s["type"] == "info_card"][0]
        check_field(scene["data"], "layout", str)

    def test_code_block_has_code(self):
        scene = [s for s in self.build()["scenes"] if s["type"] == "code_block"][0]
        check_field(scene["data"], "code", str)
        check_field(scene["data"], "language", str)

    def test_outro_has_cta_text(self):
        scene = [s for s in self.build()["scenes"] if s["type"] == "outro"][0]
        check_field(scene["data"], "cta_text", str)

    # ── Animation contract (optional but structured) ──

    def test_animation_structure_if_present(self):
        scenes = self.build()["scenes"]
        for i, s in enumerate(scenes):
            anim = s.get("animation")
            if anim and isinstance(anim, dict):
                anim_type = anim.get("type")
                assert anim_type is not None, \
                    f"Contract breach: scenes[{i}].animation.type required if animation present"